# Engenharia de Atributos: Análise RFM

Neste notebook, consolidamos os dados transacionais para criar o perfil de **Recência, Frequência e Valor Monetário (RFM)** de cada cliente.

### O que é RFM?
- **Recência (R)**: Dias desde a última compra do cliente.
- **Frequência (F)**: Quantidade total de compras realizadas.
- **Valor Monetário (M)**: Valor total gasto pelo cliente.

In [8]:
import pandas as pd
from datetime import datetime

# Carregando os dados pré-processados
df = pd.read_csv('../data/df_clientes_header.csv')

In [15]:
df_rfm = df.rename(columns={
    'valor_total': 'Monetario',
    'total_compras': 'Frequencia'
})

data_hoje = pd.to_datetime('2026-06-01')

df_rfm['Recencia'] = (data_hoje - pd.to_datetime(df_rfm['data_da_ultima_compra'])).dt.days

print("Base carregada para análise RFM.")

Base carregada para análise RFM.

In [16]:
df_rfm.head(1)

,cliente_id,avg_desconto,tempo_atividade_dias,propensao_promo,mes_pico_compra,Monetario,data_da_ultima_compra,idade,tenure_dias,qtde_compras,cat_Escrita,cat_Papelaria,Recencia
0,CUST-1000,0.631429,73.0,0.0,4.0,500.67,2026-05-21,61,491,0,True,False,11.0

In [14]:
df[df['cliente_id'] == 'CUST-1000']

,cliente_id,avg_desconto,tempo_atividade_dias,propensao_promo,mes_pico_compra,valor_total,data_da_ultima_compra,idade,tenure_dias,qtde_compras,cat_Escrita,cat_Papelaria
0,CUST-1000,0.631429,73.0,0.0,4.0,500.67,2026-05-21,61,491,0,True,False

### 1. Cálculo do RFM por Cliente

In [ ]:
# Agrupando por cliente
df_rfm = df_vendas.groupby('cliente_id').agg({
    'data_venda': lambda x: (data_referencia - x.max()).days, # Recência
    'produto_id': 'count',                                   # Frequência
    'preco_praticado': lambda x: (x * df_vendas.loc[x.index, 'qtd_vendida']).sum() # Monetário
})

# Renomeando colunas
df_rfm.columns = ['recencia', 'frequencia', 'monetario']

df_rfm.head()